### ISSUE TITLE
nTSecurityDescriptor

### ISSUE THREAD

**Issue by s0i37** [shellster/LDAPPER#2]
Hello.
I cant obtain the `nTSecurityDescriptor` attribute.

**Comment by shellster** [comment]
I need more information if you would like any help.  Please provide me with the version of LDAPPER you were using, and the command you were attempting to run as well as what message you got, and what you expect.

**Comment by s0i37** [comment]
I try to:
`python3 ldapper.py --domain company.org --user username --server 10.0.0.1 --search '(samaccountname=target)' nTSecurityDescriptor`
Output:
`   ntsecuritydescriptor: `

I hear that obtaining `nTSecurityDescrriptor` is a bit tricky. With linux-tools I can reproduce it as:
`ldapsearch -LLL -o ldif-wrap=no -E '!1.2.840.113556.1.4.801=::MAMCAQc=' -D username@compay.org -x -W -H ldap://10.0.0.1 -b DC=company,DC=org '(sAMAccountName=target)' nTSecurityDescriptor`
But I obtain raw binary data. Probably it is exists anything approach to parse LDAP ACL on linux side.

**Comment by shellster** [comment]
I'll take a look this weekend and see what I can come up with.

**Comment by shellster** [comment]
One thing I would recommend trying in the meantime, is try both LDAP engines.  It is possible one will work better than the other.

**Comment by shellster** [comment]
Maybe the account you are using doesn't have permission?  I just tried on the latest version, on both engines and it worked:

        python ldapper.py -S <redacted> -D WINDEV.local -U Administrator -P '<redacted>' -e impacket -n1 -s 1 -m1  ntsecuritydescriptor

         Guest

         ntsecuritydescriptor: \x01\x00...

**Comment by s0i37** [comment]
Yes, because you used domain admin account.
The main idea is obtaining `ntsecuritydescriptor` with domain user account.
The second problem is parsing `ntsecuritydescriptor` attribute.
All this needed for ACL attack analysis. But it seems to me that this is not feasible with Linux. All implementation use powershell.

**Comment by shellster** [comment]
I can't help you with elevation.  Since the application does return a ntSecurityDescriptor when you have the right levels of permissions, the tool isn't broken.  However, in it's current form it isn't particularly useful.  If you want that data in a useful format, you'll need to look online for how to parse it.  Might be a nice feature at some point for LDAPPER, but if you get around to it, please consider contributing a PR.

**Comment by s0i37** [comment]
It seems I've been found solve - https://github.com/skelsec/msldap
This tool can obtain any `nTSecurityDescriptor` and parse `DACL`:
```
msldap 'ldap+ntlm-password://company\user:pass@10.0.0.10'
login
getsd dc=company,dc=org
```
